AboutToCreateBackup = "You are going to create a backup of the vault in the following location:"
BackupReEncryptNotice = "Warning: You are using re-encryption mode. This will change the vault encryption key. Also, any additional accounts won't be moved to the backup."
CacheSize = "Current cache size: {{.Elements}} elements"
CacheSizeSet = "Cache size set to {{.Elements}} elements."
CertificateFile = "Certificate file"
ChoosePort = "Please, choose a port for the backend to listen."
CodecWarning = "Warning: Could not detect an encoder for H.264 in your FFMpeg installation. The will lead to errors when trying to encode videos."
CommandDescription = "Launches a vault with an interactive command line to manage it."
ConfigChangesSaved = "Changes in configuration successfully saved."
ConfiguredAddress = "Configured listening address as {{.Address}}"
DisableSSLAsk = "Do you want to disable SSL for your vault?"
EnsurePEM = "Make sure it is correct and it is in PEM format."
EnterPassword = "Enter Password"
EnterUsername = "Enter Username"
Error = "Error: {{.Message}}"
ErrorBackendBin = "Error: Could not find the backend binary (pmvd)"
ErrorBackupBin = "Error: Could not find the backup tool binary (pmv-backup)"
ErrorBackupUsage = "Usage: backup [path] - Makes a backup of the vault in the specified path"
ErrorBrowser = "Error: could not open browser: {{.Message}}"
ErrorCacheSizeUsage = "Usage: cache-size [size] - Sets the cache size"
ErrorCodecBin = "Error: Could not find the ffmpeg binary (ffmpeg)"
ErrorEncoderFound = "Error: Encoder not found in FFMpeg: {{.Codec}}"
ErrorEncoderFound2 = "Run 'ffmpeg -encoders' to check the list of available encoders."
ErrorFileExplorer = "Error: could not open file explorer: {{.Message}}"
ErrorFileNotFound = "Error: File not found: {{.File}}"
ErrorFrontMissing = "Error: Could not find the frontend package directory"
ErrorHostNameInvalid = "Error: Invalid hostname provided"
ErrorHostUsage = "Usage: host [hostname] - Sets the vault hostname for the browser"
ErrorInvalidKeyPair = "Invalid SSL key pair provided. Please fix it with 'ssl-setup'."
ErrorLocalUsage = "Usage: local [y/n] - Sets local listening mode"
ErrorLogDebugUsage = "Usage: debug [y/n]"
ErrorLogRequestsUsage = "Usage: log-requests [y/n]"
ErrorPasswordBlank = "Password cannot be blank."
ErrorPasswordNotMatching = "Passwords do not match."
ErrorPasswordTooLong = "Password cannot be longer than 255 characters."
ErrorPortBusy = "Cannot listen to port {{.Port}}. Probably there is another process listening on that port."
ErrorPortUsage = "Usage: port [p] - Sets the listening port"
ErrorProbeBin = "Error: Could not find the ffprobe binary (ffprobe)"
ErrorReEncryptUsage = "Usage: re-encrypt [path] - Makes a re-encrypted backup of the vault in the specified path"
ErrorUsernameBlank = "Username cannot be blank."
ErrorUsernameTooLong = "Username cannot be longer than 255 characters."
ErrorVaultLocked = "Vault is locked by another process. Cannot start."
FFMpegBin = "FFMpeg path [{{.DefaultPath}}]"
FFMpegBinaryTag = "FFMpeg binary: {{.File}}"
FFProbeBin = "FFProbe path [{{.DefaultPath}}]"
FFProbeBinaryTag = "FFProbe binary: {{.File}}"
FilesMissing = "Seems like some required files are missing."
H264Codec = "H.264 encoder [{{.DefaultEncoder}}]"
H264CodecTag = "H.264 encoder: {{.Encoder}}"
IsCorrectAsk = "Is this correct?"
LaunchingBrowser = "Launching browser: {{.URL}}"
ListeningModeAll = "Listening mode: All interfaces"
ListeningModeLocal = "Listening mode: Local"
ListeningPort = "Listening port: {{.Port}}"
ListeningPortChanged = "Listening port changed: {{.Port}}"
LocalHostBindAsk = "Do you want to bind to localhost?"
LocalHostBindDesc = "by selecting no, it will bind all network interface"
LogDebugDisabled = "Debug logging is now DISABLED."
LogDebugEnabled = "Debug logging is now ENABLED."
LogFile = "Log file: {{.File}}"
LogRequestsDisabled = "Requests logging is now DISABLED."
LogRequestsEnabled = "Requests logging is now ENABLED."
ManualCacheSize = "cache-size [size] - Sets the cache size"
ManualCommandBackup = "backup [path] - Makes a backup of the vault in the specified path"
ManualCommandBrowser = "browser - Opens the vault using the default browser"
ManualCommandClean = "clean - Restarts the vault and cleans inconsistent files"
ManualCommandExit = "exit - Closes the vault and exits the program"
ManualCommandFFMpeg = "ffmpeg - Prints FFMpeg configuration"
ManualCommandFFMpegSetup = "ffmpeg-setup - Setups FFMpeg binary paths and codecs"
ManualCommandHelp = "help - Prints command list"
ManualCommandHostname = "host [hostname] - Sets the hostname to access the vault"
ManualCommandKeyExport = "key-export - Exports the encryption key of the vault, in order to make a backup"
ManualCommandKeyRecover = "key-recover - Recovers access to the vault, using a backup of the encryption key"
ManualCommandLocal = "local [y/n] - Sets local listening mode"
ManualCommandLogDebug = "debug [y/n] - Enables / disables debug logging"
ManualCommandLogRequests = "log-requests [y/n] - Enables / disables request logging"
ManualCommandOpenLogs = "open-logs - Opens the logs folder in the file explorer"
ManualCommandPort = "port [p] - Sets the listening port"
ManualCommandReEncrypt = "re-encrypt [path] - Makes a re-encrypted backup of the vault in the specified path"
ManualCommandRecover = "recover - Restarts the vault and recovers any non-indexed media"
ManualCommandRestart = "restart - Restarts the vault"
ManualCommandSSL = "ssl - Prints ssl configuration (if any)"
ManualCommandSSLDisable = "ssl-disable - Disables SSL (use regular HTTP)"
ManualCommandSSLSetup = "ssl-setup - Setups SSL to use HTTPS for accessing your vault"
ManualCommandStart = "start - Starts the vault"
ManualCommandStatus = "status - Prints current status and configuration"
ManualCommandStop = "stop - Stops the vault"
NoPrefix = "n"
NotSet = "(Not Set)"
OpenMultipleRisk = "Opening the vault by multiple processes could be dangerous for the vault integrity."
PMV = "Personal Media Vault"
PortNumber = "Port number"
PrivateKeyFile = "Private key file"
Proceed = "Proceed?"
ReinstallFix = "In order to fix this error, you could re-install PersonalMediaVault."
RepeatPassword = "Repeat Password"
RestartVaultAsk = "Restart the vault?"
SSLCertFile = "SSL certificate file: {{.File}}"
SSLDisabled = "SSL: Disabled"
SSLEnabled = "SSL: Enabled"
SSLNotEnabled = "SSL is not enabled for this vault."
SSLkeyFile = "SSL key file: {{.File}}"
SetupFFMpegAsk = "Do you want to setup FFMpeg configuration?"
SetupSSLAsk = "Do you want to setup SSL for your vault?"
StartingVault = "Starting vault..."
StatusStarted = "Status: Started"
StatusStopped = "Status: Stopped"
TypeCertificatePath = "Type the absolute path in your file system to the SSL CERTIFICATE file you want to use."
TypeFFMpegPath = "Type the absolute path in your file system to the FFMpeg binary you want to use."
TypeFFProbePath = "Type the absolute path in your file system to the FFProbe binary you want to use."
TypeH264Codec = "Type the name of the encoder to use for H.264 video."
TypePrivateKeyPath = "Type the absolute path in your file system to the SSL PRIVATE KEY file you want to use"
UnrecognizedCommand = "Unrecognized command: '{{.Command}}'. Use 'help' to get the command list."
Usage = "Usage: pmv [PATH]"
VaultAlreadyStarted = "Vault is already started. Use 'browser' to open it in the browser."
VaultAlreadyStopped = "Vault is already stopped."
VaultBeingUsed = "Seems like the vault is being used by another process"
VaultHostname = "Vault host: {{.HostName}}"
VaultInitialized = "Vault initialized successfully!"
VaultListeningAddress = "Vault listening address: {{.Address}}"
VaultNotFoundCreateAsk = "Vault folder does not exists, do you want to create it?"
VaultNotFoundCreateOne = "Vault does not exists. Please provide a set of credentials to create one."
VaultPath = "Vault path: {{.Path}}"
VaultStartError = "Could not start the vault. Check logs for details"
VaultStartedSuccessfully = "Vault successfully started."
VaultStoppedSuccessfully = "Vault successfully stopped."
VaultStopping = "Stopping vault..."
Version = "Version"
YesNo = "y/n"
YesPrefix = "y"
