[package]
name = "pmv-launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "5.3.2"
rfd = "0.15.4"
slint = {version= "1.12.1", features = ["gettext"]}

[build-dependencies]
slint-build = "1.12.1"
